### ISSUE TITLE
Bug with gases in UV region

### ISSUE THREAD

**Issue by mcduffie** [ReFRACtor/ABSCO#13]
I get the following error:

```
TAPE5_BRO_P0000.0384_T290.0K_26310-28310
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
STOP  LBLRTM EXIT
TAPE5_BRO_P0000.0384_T300.0K_26310-28310
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
STOP  LBLRTM EXIT
TAPE5_BRO_P0000.0384_T310.0K_26310-28310
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
STOP  LBLRTM EXIT
TAPE5_BRO_P1013.9480_T190.0K_28310-30310
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
STOP  LBLRTM EXIT
Traceback (most recent call last):
  File "./run_LBLRTM_ABSCO.py", line 106, in <module>
    kObj.calcABSCO(mol)
  File "/home/mcduffie/Devel/refractor/absco_aer/ABSCO_compute.py", line 705, in calcABSCO
    kernel = self.degradeKern[iBand]
IndexError: list index out of range
```
When using this configuration of wavenumbers and molecules:

```
When using this config:
26,27c26,27
> wn1 = 26310
> wn2 = 33340
43c43
> molnames = BRO H2CO NO2 O2 O3 SO2
```

**Comment by mcduffie** [comment]
This bug has happened for both BRO and H2CO so far.

**Comment by pernak18** [comment]
@mcduffie try the latest commit (e27a3c34badbf1573b8ee8f3a6eb39c96b8b73d9). the fix worked for me.

**Comment by pernak18** [comment]
@mcduffie for clarity, this was an issue of bandwidth, not the UV region. LBL can only handle 2000 cm-1 bands at a time, and i did not implement that restriction with the spectral degradation code correctly.

**Comment by mcduffie** [comment]
Thanks its working for me. My only problem now is running out of memory.
